modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.guillotina_granizados]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.guillotina_granizados]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.guillotina_granizados]]
    modId="crystaldrops"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
    modId="guillotina_granizados"
    version="1.0.0"
    displayName="Guillotina Granizados"
    description='''
        Granizados inspirados en Guillotina Granizados de Medellín.
        Tómalos para obtener efectos poderosos... y un poco de náusea.
        Compatible con CrystalDrops: los mobs de mayor tier sueltan mejores ingredientes.
    '''
