plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = '1.0.0'
group = 'net.sherfy.crystaldrops'
archivesBaseName = 'crystal-drops-addon'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment', version: '2023.09.03-1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                crystaldrops { source sourceSets.main }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                crystaldrops { source sourceSets.main }
            }
        }
    }
}

repositories {
    maven { url 'https://maven.parchmentmc.org' }
    flatDir { dirs '../mod-src' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
    // Crystal Leveling mod as compile-time dependency
    compileOnly fileTree(dir: '../mod-src', include: ['*.class'])
}

jar {
    manifest {
        attributes([
            'Specification-Title'   : 'crystal-drops-addon',
            'Specification-Version' : '1',
            'Implementation-Title'  : project.name,
            'Implementation-Version': project.jar.archiveVersion
        ])
    }
}
